[env:bluepill_f103c8]   ;STM32duino
platform = ststm32 ;STM32duino
board = bluepill_f103c8 ;STM32duino

framework = arduino
monitor_port = COM6
monitor_speed = 115200
upload_port = COM6
upload_speed = 921600
;upload_protocol = dfu
upload_protocol = serial ;para FTDI (RX - A9, TX - A10, GND - GND, 5V - 5V)
lib_ldf_mode = deep+
lib_deps =

# Accept new functionality in a backwards compatible manner and patches
  stm32duino/STM32duino Low Power @ ^1.5.0
  stm32duino/STM32duino RTC @ ^1.8.0
  
  ; sandeepmistry/LoRa @ 0.7.2
  ; teckel12/NewPing @ 1.9.1